version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   
      - "9001:9001"  

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
      - minio
    ports:
      - "8080:8080"   

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"  

volumes:
  mongo_data:
  minio_data:







Request URL
https://rayok.bank.si/api/event
Request Method
POST
Status Code
500 Internal Server Error
Remote Address
72.56.14.18:443
Referrer Policy
strict-origin-when-cross-origin
access-control-allow-origin
*
connection
keep-alive
content-length
58
content-type
application/json; charset=utf-8
date
Wed, 15 Apr 2026 18:02:22 GMT
etag
W/"3a-LK9iu6dpBX/KGvrit6pkEUKlT/I"
server
nginx/1.24.0 (Ubuntu)
x-powered-by
Express
accept
*/*
accept-encoding
gzip, deflate, br, zstd
accept-language
en-GB,en-US;q=0.9,en;q=0.8,ru;q=0.7
connection
keep-alive
content-length
187066
content-type
multipart/form-data; boundary=----WebKitFormBoundaryjMYNACBFSJ9p5HtH
host
rayok.bank.si
origin
https://rayok.bank.si
referer
https://rayok.bank.si/admin/event/new
sec-ch-ua
"Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"
sec-ch-ua-mobile
?1
sec-ch-ua-platform
"iOS"
sec-fetch-dest
empty
sec-fetch-mode
cors
sec-fetch-site
same-origin
user-agent
Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/604.1